FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm install -g nodemon
COPY . .
RUN npx prisma generate

EXPOSE 8080
RUN adduser -D appuser
USER appuser

CMD ["npm", "run", "dev"]